apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapp1            # ← УНИКАЛЬНОЕимя
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app1            # ← ДРУГОЙ namespace
  source:
    path   : "HelmCharts/MyChart2"
    repoURL: "git@github.com:minara2/argocd1.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_dev.yaml
      parameters:
        - name: "container.image"
          value: temson13/temson13

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
