apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapp4
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: app4
  source:
    path   : "HelmCharts/MyChart2"
    repoURL: "git@github.com:minara2/argocd1.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml
      parameters:
      - name: "container.image"
        value: minara22/k8s_minara

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
